spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/testdatabase
    username: sa
    password: bhu8BHU*
  jpq:
    databse-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          globally_quoted_identifiers: true
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  mvc:
    async:
      request-timeout: 30000
server:
  port: 8081
  error:
    path: /user/error
    whitelabel:
      enabled: false
